"""Added old_ctc column to increment_history

Revision ID: 817c7543a001
Revises: b01c75453fc8
Create Date: 2026-02-20 16:43:11.385803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c7543a001'
down_revision = 'b01c75453fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('increment_per_month')

    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_ctc', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('increment_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('new_ctc', sa.Float(), nullable=False))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('generated_by',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('old_increment')
        batch_op.drop_column('new_increment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_increment', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('old_increment', sa.FLOAT(), nullable=True))
        batch_op.alter_column('generated_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('new_ctc')
        batch_op.drop_column('increment_amount')
        batch_op.drop_column('old_ctc')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('increment_per_month', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
