"""add drive_file_id to document

Revision ID: b5771f86d7f1
Revises: 817c7543a001
Create Date: 2026-02-23 11:17:55.528157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5771f86d7f1'
down_revision = '817c7543a001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('drive_file_id')

    # ### end Alembic commands ###
