"""Add drive_folder_id to Employee

Revision ID: c4774f13c0ef
Revises: e0c793b2a3c1
Create Date: 2026-02-23 15:17:14.432747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4774f13c0ef'
down_revision = 'e0c793b2a3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')

    # ### end Alembic commands ###
