"""Remove duplicate increment_history relationship

Revision ID: e0c793b2a3c1
Revises: b5771f86d7f1
Create Date: 2026-02-23 13:52:54.738588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c793b2a3c1'
down_revision = 'b5771f86d7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_ctc', sa.Float(), nullable=True))
        batch_op.drop_column('ctc')

    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ctc', sa.FLOAT(), nullable=True))
        batch_op.drop_column('base_ctc')

    # ### end Alembic commands ###
